### ISSUE TITLE
What are the units for the values in the response payloads?

### ISSUE THREAD

**Issue by mpfilbin** [ambient-weather/api-docs#1]
For example, if I issue this request:

Request:

`http get https://api.ambientweather.net/v1/devices/<Device MAC Address>?apiKey=<API Key>&applicationKey=<Application Key>&endDate=<unix timestamp>&limit=<n>`

Response:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
...
Via: 1.1 vegur
X-Powered-By: Express
```
```json
[
    {
        "baromabsin": 24.53,
        "baromrelin": 29.73,
        "dailyrainin": 0,
        "date": "2018-02-09T17:10:00.000Z",
        "dateutc": 1518196200000,
        "dewPoint": 25.50795428285515,
        "feelsLike": 27,
        "hourlyrainin": 0,
        "humidity": 94,
        "humidityin": 27,
        "lastRain": "2018-02-02T16:59:00.000Z",
        "maxdailygust": 13.6,
        "monthlyrainin": 0.01,
        "solarradiation": 49.79,
        "tempf": 27,
        "tempinf": 61,
        "totalrainin": 0.34,
        "uv": 0,
        "weeklyrainin": 0,
        "winddir": 49,
        "windgustmph": 2.2,
        "windspeedmph": 2
    },
    ...
]
```
Is this something that is driven by the preferences we set up in our ambientweather.net dashboard?

**Comment by lrosenman** [comment]
The units are in the field name and also on the https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs page. 

Feel free to ping me with corrections.

**Comment by mpfilbin** [comment]
Ah, thank you @lrosenman for pointing that out, I should have looked more closely at the output. Do you know if there would be any interest in supporting SI units in the future?

**Comment by lrosenman** [comment]
Probably not, as most weather website software, etc. can deal with US units, and AmbientWeather.net is directed at US-Based consumers.  That said @owise1 is the final arbiter of that.

**Comment by owise1** [comment]
Hi @mpfilbin, 

Sorry, there are no plans to support that.  It would just overcomplicate things too much. Conversions will have to be done on your end.
