### ISSUE TITLE
Comprehensive list of station types and JSON elements

### ISSUE THREAD

**Issue by mhilbush** [ambient-weather/api-docs#11]
Sorry for opening all these issues...

Is there a comprehensive list of the station types (and associated JSON elements) supported on `ambientweather.net`? In my openHAB smarthome integration project, I'd like to support more stations than the two I currently own (WS-1400-IP and WS-8482).

Alternatively, is there a test API key that I could use that has a variety of stations associated with it?

Also, for the real-time API, is it possible for the `subscribed` JSON object to include an identifier ID of the weather station model? I would like to use this to auto-discover the different station types associated with a subscription.

**Comment by owise1** [comment]
It'd be nice for us too, but unfortunately most devices don't send their station type.  This is the exhaustive list of device params: https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs

**Comment by mhilbush** [comment]
Thanks. I saw that list. Unfortunately, that looks like a generic list of all possible data elements. I was looking for the specific data elements returned for each station type. The alternative would be a test API key that returned data objects for some or all stations.

I realize this is not necessary to parse the JSON. My goal was to expose [channels](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channels) just for the data elements for each Ambient Weather [thing](https://www.eclipse.org/smarthome/documentation/development/bindings/how-to.html#describing-things). Sorry for the use of the openHAB-specific terms.
