### ISSUE TITLE
Can't hardcode an application key

### ISSUE THREAD

**Issue by bachya** [ambient-weather/api-docs#14]
Home Assistant currently has an integration that uses the Ambient Weather REST API. In its original design, it required users to provide both an application key and an API key. Recently, [when one of our users reached out to Ambient](https://github.com/home-assistant/home-assistant/issues/19932), he had this interaction:

>Ambient weather does not want to provide app keys and has told me the developer of this should have hard coded the app key in to this.
>
>I referred them to the HA documentation and the following was the response:
>
>"Unfortunately, he is wrong. It is one app with many users, not many apps with many users. Thus, he needs to supply you with the app key unique to his application."

Although we understand the principle (the application key identifies the application and the API key identifies the user), we can't use this approach. We are an open source, GitHub-hosted project; if we hardcode an application key into our integration, it will be available for the entire world to see. Although an API key is still required to use the API, enterprising Google users could simply hunt around, find our application key, pair it with their own API key, and go to town.

Would you be willing to collaborate with us on a different authentication mechanism that accomplishes your purposes, but also adequately supports the fact that we are public and open source? Or, if a "more correct" mechanism already exists, could you point us to it?

Thanks!

**Comment by ambientweather** [comment]
The issue is that it is time consuming since we review each app key.
I would not worry about posting the app key. I doubt anyone will do anything nefarious with it. 
Anyone that writes their own application will want their own app key.
Thanks
Ed

**Comment by bachya** [comment]
Thanks, Ed – we'll accommodate. Closing this issue.

**Comment by owise1** [comment]
@bachya Update on this. In the next week we'll be allowing users to create their own application API keys. In light of that, I think it's probably best not to publish your application key. Are you able to hang tight for a week?

**Comment by bachya** [comment]
@owise1 Yes; we'll re-open and hold for now.

**Comment by owise1** [comment]
ok. That feature is out. You may need to clear your cache and reload to see it.  Thanks!

**Comment by bachya** [comment]
I see it, @owise1. Thank you!
