### ISSUE TITLE
devices endpoint not working

### ISSUE THREAD

**Issue by mhilbush** [ambient-weather/api-docs#18]
Calls to the devices endpoint are not working. This started some time on August 2.

When calling the v1 devices endpoint (https://api.ambientweather.net/v1/devices?applicationKey=XXXX&apiKey=YYYY) with valid app and api keys, I'm getting this response.
```
{"error":"unknown-error"}
```
My Java code is throwing an exception.
```
java.util.concurrent.ExecutionException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
```

@owise1 Did something change in the API? This had been working for many months.

Also, last night around 3:15 AM EDT, the real-time API stopped sending events. This also had been working many months.

@bachya Are you seeing something similar in HA?

**Comment by owise1** [comment]
We've identified an issue. It should be coming back now, but it's going to take some time to process the backlog of data

**Comment by mhilbush** [comment]
Working again! Thanks!!
