### ISSUE TITLE
API Returning Wrong Information

### ISSUE THREAD

**Issue by rcrum003** [ambient-weather/api-docs#19]
When querying the API, I'm getting a tempf of 69.3, but in the console i'm getting 80. I've verified i'm calling the same device. Additionally, from time to time i get "{"error":"unknown-error"}".

**Comment by mhilbush** [comment]
@rcrum003 Regarding the unknown-error, I reported an occurrence of it this morning. See #18. It was working for me as of about 9 am US EDT.

**Comment by owise1** [comment]
@rcrum003 Are you still experiencing this issue?
