### ISSUE TITLE
New Helper Library - R

### ISSUE THREAD

**Issue by andrewflack** [ambient-weather/api-docs#20]
I recently built a simple R package to access the Ambient Weather API. I hope you'll consider including it in the API documentation under "Helper Libraries".

Thanks!

https://github.com/andrewflack/ambientweatheR

**Comment by ambientweather** [comment]
I will. Can you write a brief description and provide a logo or image?

Regards,

Ed.

**Comment by andrewflack** [comment]
Hi Ed,

"ambientweatheR" is an R package that makes it easy to interact with the Ambient Weather REST API, providing programmatic access to a user's weather station data. The package provides wrapper functions to list a user's devices and to fetch data for a given device.

I don't have a logo or image - I can whip something up if necessary. Let me know.

Andrew

**Comment by ambientweather** [comment]
Awesome. Any logo can do. Just send me a link or feel free to create one. 

Regards,

Ed.

**Comment by andrewflack** [comment]
Hi Ed,

[Here's a logo](https://github.com/andrewflack/ambientweatheR/blob/master/inst/figures/hex_logo.png).

Andrew

**Comment by ambientweather** [comment]
OK, done:
Community - Ambient Weather Network

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Community - Ambient Weather Network

Apps by Ambient Weather: Ambient Weather Dashboard by Ambient Weather (Android). The Ambient Weather App requir...
 |

 |

 |





Ed

_________Need help? 
Visit:
AmbientWeather.net/help 

    On Monday, August 12, 2019, 06:36:15 PM MST, Andrew Flack <notifications@github.com> wrote:  
 
 
Hi Ed,

Here's a logo.

Andrew

**Comment by andrewflack** [comment]
Awesome, thanks! Would it be too much trouble to add a link to help people find it?

**Comment by ambientweather** [comment]
Link please?


_________Need help? 
Visit:
AmbientWeather.net/help 

    On Thursday, August 15, 2019, 11:34:51 AM MST, Andrew Flack <notifications@github.com> wrote:  
 
 
Awesome, thanks! Would it be too much trouble to add a link to help people find it?

**Comment by andrewflack** [comment]
Just a link to the repo:

https://github.com/andrewflack/ambientweatheR

Thanks!
Andrew

**Comment by owise1** [comment]
Here you go: https://ambientweather.docs.apiary.io/#introduction/helper-libraries
