### ISSUE TITLE
api.ambientweather.net no longer working?

### ISSUE THREAD

**Issue by bachya** [ambient-weather/api-docs#21]
[`aioambient`](https://github.com/bachya/aioambient) has traditionally used `api.ambientweather.net` for the REST API. This evening, I noticed that the library started returning this stacktrace:

```
Cannot connect to host api.ambientweather.net:443 ssl:default [nodename nor servname provided, or not known]
```

Should this URL no longer be used? Is `dash2.ambientweather.net` still the better URL to use?

**Comment by owise1** [comment]
Are you still having this issue?

**Comment by bachya** [comment]
No – today, it appears to work with either `api.` or `dash2.`. Will close.
