### ISSUE TITLE
API reporting "battout" inconsistent with local data and dashboard on AmbientWeather.net

### ISSUE THREAD

**Issue by MikeManzo** [ambient-weather/api-docs#24]
I am seeing inconsistent battery status when using the API vs. local (Meteobridge) and [Dashboard](https://ambientweather.net/dashboard/892484c173589bea09c37f65e93e20b3) polling

Summary:
- My Dashboard on AmbientWeather.net reports "All Batteries OK"
- Polling the Meteobridge attached to the station reports "All Batteries OK"
- Using the API,"battout" returns "0".  According to the documentation, "1=Good, 0=Bad".

All other parameters returned from the API are as expected.  Is this an API issue or is the documentation correct?

Thanks in-advance.

**Comment by owise1** [comment]
it turns out that for Meteobridge users the battery param is actually flipped. i.e. 1 == low and 0 == ok. I'll update the documentation.
