### ISSUE TITLE
LastRain isn't always present

### ISSUE THREAD

**Issue by knwpsk** [ambient-weather/api-docs#31]
In my production data using the REST interface, using the devices/MacAddress endpoint: 

Within one result set, sometimes the property LastRain (dateTime) is present for a data interval, and sometimes that field/property is completely absent. 
Is this intentional, or a bug?

If it's intentional: I can code around it.... are there any other fields that are not always given?
Thanks

**Comment by knwpsk** [comment]
Maybe this only happens before the first rainfall *ever* recorded?  (My wx station is new, and I only see this happening in the first couple of days)

**Comment by owise1** [comment]
your second comment is correct. LastRain *should* always be there after the first rain

**Comment by knwpsk** [comment]
Thanks, Oliver.
