### ISSUE TITLE
Real-time API doesn't work

### ISSUE THREAD

**Issue by wadetregaskis** [ambient-weather/api-docs#42]
I'm trying to use the realtime API via Socket.IO (for https://github.com/wadetregaskis/SwiftWeather) and I am able to connect but I never receive any response to anything I send.  I _do_ receive pings from the server, so something is actually active on the other end, but the "subscribe" command appears to just be silently ignored by the server…?

The documentation here in this repo isn't all that helpful since it refers specifically and exclusively to a random Node.js library, without actually documenting the protocol in any meaningful way.  So I don't really know what the argument to "subscribe" is supposed to be at the Socket.IO layer let-alone the wire layer.  The source of https://github.com/owise1/ambient-weather-api seems to imply that something like the string '{ "apiKeys": ["xyz"] }' should work, being the JSON serialisation of a nominal object with an apiKeys property etc.  But it doesn't.  Nor does any conceivable variation on serialisation format (e.g. single-quotes instead of double-quotes, no quotes, etc).  Nor if I send the serialised form as a binary event.  Etc.

**Comment by mhilbush** [comment]
If you want to look at an implementation (in Java), here's one I wrote to integrate the realtime API into the openHAB smarthome platform.

https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.ambientweather

**Comment by wadetregaskis** [comment]
Thanks.  Unfortunately that sheds no light on the issue.  You're doing seemingly the exact same thing I am.  Yet the server never, ever responds to the "subscribe" command for me.

In fact it never responds to _anything_ I send.  I just get its pings every 25 seconds.  That's the only sign of life.

**Comment by mhilbush** [comment]
Hmm. Sorry, I'm not sure what to suggest.

I don't know swift, so I can't really provide much help. I didn't see any of the Socket.IO code in the repo you posted above, so maybe it's in a local branch?

I assume you are setting up a handler/callback for the "subscribed" event? Such as what I'm doing [here](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherEventListener.java#L167)

**Comment by wadetregaskis** [comment]
Indeed I haven't pushed any of this [attempted] support to GitHub yet - seems pointless if it doesn't work.

I installed [Charles proxy](https://www.charlesproxy.com) to snoop the actual WebSockets traffic, and it seems to confirm that I'm doing everything correctly.  The server just simply never responds to anything.  e.g. with EIO v4 to rt2.ambientweather.net:

<img width="680" alt="rt2 ambientweather net" src="https://user-images.githubusercontent.com/863283/184801664-80a13491-83b0-4bb0-bbb0-ebafba30f863.png">

…or with EIO v3 to api.ambientweather.net:

<img width="674" alt="api ambientweather net" src="https://user-images.githubusercontent.com/863283/184801692-e1406c83-980f-4d19-bc38-e6ec77f07a41.png">

Per the [Socket.IO Protocl Spec](https://github.com/socketio/socket.io-protocol/tree/v4#packet-encoding), that's all exactly correct.

Note that in the screenshots above I replaced my API key with a dud value to preserve my API key's secrecy, but of course in real testing I'm using my real API key - the same API key that works just fine with the basic HTTP APIs.

**Comment by wadetregaskis** [comment]
I'm going to have to give up on supporting the 'Live' API in my library.  I've run out of things to try, even blindly.  All evidence suggests the AmbientWeather API is broken. 😔

I've stashed [my hacky work-in-progress code in a branch](https://github.com/wadetregaskis/SwiftWeather/tree/AmbientWeatherLive), for posterity I guess.
