### ISSUE TITLE
Rain Fields explanation

### ISSUE THREAD

**Issue by WxBoxOnline** [ambient-weather/api-docs#46]
What is the meaning of each field:

dailyrainin - Daily Rain, in
24hourrainin - 24 Hour Rain, in
weeklyrainin - Weekly Rain, in
monthlyrainin - Monthly Rain, in
yearlyrainin - Yearly Rain, in
eventrainin - Event Rain, in

How is dailyrainin different from 24hourrainin? When are they reset?
Is weeklyrainin since XXX time on the previous Sunday? If so, what is that XXX time that it gets reset?
Is monthlyrainin since XXX time on the first day of the current month? If so, what is that XXX time that it gets reset?
... same for yearlyrainin ...

And... eventrainin... what does it represent? When does it get reset?

**Comment by owise1** [comment]
https://ambientweather.com/faqs/question/view/id/1454/
