### ISSUE TITLE
Incomplete listing of possible JSON device variables in current list.

### ISSUE THREAD

**Issue by ktrue** [ambient-weather/api-docs#5]
While debugging a problem with a non-Davis weather station, I discovered that the station was posting yearly rain as "totalrainin" in the JSON instead of the documented "yearlyrainin". I also found that station also reported "weeklyrainin", "eventrainin", and ""lastRain" values.

The (likely Davis-specific) variables of "windgustdir", "winddir_avg2m", "windspdmph_avg2m", "winddir_avg10m", and "windspdmph_avg10m" were also missing from that station.

Could the docs on apiary and the GitHub docs be updated to include ALL the possible fields returned from a device query AND an indication of any variables that are only specific to a particular weather station?

**Comment by ambientweather** [comment]
I would have to contact our WeatherBridge to see if it is possible to add these as parameters.
Thanks
Ed

**Comment by owise1** [comment]
Here's the list of all the possible parameters: https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs
