### ISSUE TITLE
AQI PM25 missing in data on website and in API (outdoor)

### ISSUE THREAD

**Issue by btbenedi** [ambient-weather/api-docs#50]
I have a WS-2902D and just added a PM25 outdoor sensor.

The sensor is reporting properly on website and API, I can see the ug/m3 pollutant concentration value, however there is no AQI derived from PM25 data.

If I download the CSV, I get PM2.5 Outdoor and PM2.5 Outdoor 24 Hour Average

In the API, I receive `pm25` and `pm25_24h`

However per documentation [here](https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs), I should also be receiving `aqi_pm25` and `aqi_pm25_24h`

**Comment by owise1** [comment]
you are correct. the documentation is wrong here. Unfortunately the PM25 outdoor sensor does not calculate/send aqi.  It's not hard to calculate though. Here is an article that has the common calculations: https://smartairfilters.com/en/blog/difference-pm2-5-aqi-measurements/
