### ISSUE TITLE
yearly rain inches param feature

### ISSUE THREAD

**Issue by grantiago** [ambient-weather/api-docs#55]
The [docs ](https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs) say yearlyrainin is available. Though with the cavaet *Note: Not all devices send all the parameters.*

When I query the api, with python requests there is no __yearlyrainin__ . Additionally there is no yearlyrainin using the suggested python libraries as well `https://github.com/bachya/aioambient`

My weather stations: WS-2902 c and WS-2902-a. Flagship Ambient products. Yearly Rain is an important param. Total Rain is useless. 

`"lastData": {
        "dateutc": 1734448980000,
        "tempinf": 65.7,
        "humidityin": 42,
        "baromrelin": 30.42,
        "baromabsin": 27.369,
        "tempf": 36.7,
        "battout": 1,
        "humidity": 97,
        "winddir": 233,
        "windspeedmph": 0,
        "windgustmph": 0,
        "maxdailygust": 6.9,
        "hourlyrainin": 0,
        "eventrainin": 0.618,
        "dailyrainin": 0.181,
        "weeklyrainin": 0.669,
        "monthlyrainin": 1.421,
        "totalrainin": 34.772,
        "solarradiation": 5.31,
        "uv": 0,
        "batt_co2": 1,
        "feelsLike": 36.7,
        "dewPoint": 35.93,
        "feelsLikein": 65.7,
        "dewPointin": 42,
        "lastRain": "2024-12-17T10:36:00.000Z",
        "tz": "America/Boise",
        "date": "2024-12-17T15:23:00.000Z"
    },`

**Comment by owise1** [comment]
please contact support@ambientweather.com for help with this. if your station is sending it, it should show up in the API. is yearly rain showing up on  your dashboard? i would think your station should be sending it so maybe they can help.
