### ISSUE TITLE
Socket.io connection reconnects every 2-3 minutes

### ISSUE THREAD

**Issue by mhilbush** [ambient-weather/api-docs#8]
I'm implementing a service to integrate Ambient Weather into the openHAB home automation platform.

I've got it working pretty well, and I'm currently getting data events for my WS-1400-IP and the WS-8482.

However, every 3 minutes or so, I see a disconnect followed by a reconnect. I'm not sure what's causing this. To deal with it, I'm sending a subscribe command every time the reconnect happens. While not a major problem to do this, it does seem pretty inefficient.

I'm using the Java socket.io client software from here.
https://github.com/socketio/socket.io-client-java

**Comment by mhilbush** [comment]
Adding a little more info on what I'm seeing.
```
2018-12-06 17:46:23.706 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_PING received
2018-12-06 17:46:23.790 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_PONG received
2018-12-06 17:46:48.791 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_PING received
2018-12-06 17:46:53.793 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_DISCONNECT received
2018-12-06 17:47:05.295 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_CONNECT_ERROR received
2018-12-06 17:47:08.365 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_RECONNECT received
2018-12-06 17:47:08.372 [DEBUG] [.handler.AmbientWeatherEventListener] - EVENT_CONNECT received
```

If you need to see my code, it's here.
https://github.com/mhilbush/openhab2-addons/tree/ambient-weather-binding/addons/binding/org.openhab.binding.ambientweather

**Comment by owise1** [comment]
Thanks for letting us know. We're aware of this issue and working on it.

**Comment by mhilbush** [comment]
Thanks. I'm new to socket.io, and thought it might be something I was doing (or not doing).

**Comment by owise1** [comment]
Hi @mhilbush , I'm not sure if you're still working on this project, but if you are, would you mind trying your socket connection using the domain "dash2.ambientweather.net" instead of "api.ambientweather.net" and let me know if the disconnects keep happening.  We've been having load balancer issues and I'm experimenting with a workaround.  If it's too much trouble no problem.  thx.

**Comment by mhilbush** [comment]
Sure, I'll try it in a couple minutes and report back what I'm seeing.

**Comment by owise1** [comment]
Wonderful. Thanks for your help. Feel free to keep using that domain if you like. We're going to start transitioning things to it, so it'll stay up.

We actually don't cycle the servers any more unless it's necessary.

**Comment by mhilbush** [comment]
Ok, sounds good! Much appreciated.

**Comment by mhilbush** [comment]
Just wanted to close this out... No disconnects since 8 pm EST last night. I'll close this issue now.
